wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.5
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1686386478.799853
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.9.5
      5: 0.15.3
      8:
      - 1
      - 3
      - 5
